name: Build

on:
  push:
    tags:
      - v*.*.*
  schedule:
    - cron: '0 16 1,15 * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: multi-platform/debian/sid/
          platforms: ${{ vars.DOCKER_ALL_PLATFORMS }}
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/debian:sid
            ghcr.io/${{ github.repository_owner }}/debian:sid
